name: developemnt workflow
on: [push]

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      # clone the repo first
      - name: First Check Out REPO
        uses: actions/checkout@v7
        with:
          repository: ${{ github.repository }}

      - name: LIST ALL THE FILES
        run: ls -ltr

      - name: show which os-version is being used RIGHT NOW
        run: cat /etc/os-release

      - name: show the GITHUB_REPOSITORY which is currently being used !!!
        run: echo ${{github.repositoryUrl}}

      - name: INSTALL WHATEVER SOFTWARE IT NEEDS
        run: npm install

      - name: RUN THE TESTS
        run: npm run test >> test.log

  test:
    needs: development
    runs-on: ubuntu-latest

    steps:
      - name: GET THE TEST FILE FROM PREVIOUS JOB
        uses: actions/upload-artifact@v7
        with:
          name: test-artifact
          path: test.log
      - name: SEE THE TEST
        run: cat test.log
