name: developemnt workflow
on: [push]

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      # clone the repo first
      - name: First Check Out REPO
        uses: actions/checkout@v7
        with:
          repository: ${{ github.repository }}

      - name: LIST ALL THE FILES
        run: ls -ltr

      - name: show which os-version is being used RIGHT NOW
        run: cat /etc/os-release

      - name: show the GITHUB_REPOSITORY which is currently being used !!!
        run: echo "CURRENT REPO: ${{ github.repository }} "
